version: "3"
networks:
  expense:
volumes:
  mysql:  #docker volume create mysql
services:
  mysql:
    image: ramanji4/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
    networks:
    - expense
  backend:
    image: ramanji4/backend:v1
    container_name: backend
    command: sh -c "sleep 60 && node /opt/server/index.js"
    depends_on:
    - mysql
    networks:
    - expense
  frontend:
    image: ramanji4/rootfrontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
    networks:
    - expense